/* game/common/spchevnt.h — reconstructed from game/common/spchevnt.c (53 fns) */
#ifndef _GAME_COMMON_SPCHEVNT_H_
#define _GAME_COMMON_SPCHEVNT_H_
#include "../../nfs4_types.h"

extern "C"
{
    long SPCHNFS_C_A_CONFIRM(SPCHNFSType_VOICE *VOICE, int ID_UNIT, SPCHNFSType_CONFIRM *CONFIRM); /* :7 */
}
extern "C"
{
    long SPCHNFS_C_D_REQUEST_EMS(SPCHNFSType_VOICE *VOICE, SPCHNFSType_AMBULANCE *AMBULANCE); /* :27 */
}
extern "C"
{
    long SPCHNFS_D_C_BEGIN_PURS_REP_SPDR(SPCHNFSType_COLOUR *COLOUR, int ID_CAR, SPCHNFSType_POSITION *POSITION, int ID_LOCATION, SPCHNFSType_DISTANCE *DISTANCE); /* :66 */
}
extern "C"
{
    long SPCHNFS_C_D_ENGAGE_PURS_REP_SPDR_REPLY(SPCHNFSType_VOICE *VOICE, int ID_UNIT, SPCHNFSType_COLOUR *COLOUR, int ID_CAR, SPCHNFSType_DISTANCE *DISTANCE, SPCHNFSType_POSITION *POSITION, int ID_LOCATION, SPCHNFSType_CONFIRM *CONFIRM); /* :94 */
}
extern "C"
{
    long SPCHNFS_C_D_ENGAGE_PURS_REP_SPDR(SPCHNFSType_VOICE *VOICE, SPCHNFSType_COLOUR *COLOUR, int ID_CAR, SPCHNFSType_POSITION *POSITION, int ID_LOCATION, SPCHNFSType_DISTANCE *DISTANCE, int ID_SPEED, SPCHNFSType_vs_KMH_MPH *vs_KMH_MPH, SPCHNFSType_PERP_NAME *PERP_NAME); /* :126 */
}
extern "C"
{
    long SPCHNFS_C_C_IN_PURS_NEAR_PERP(SPCHNFSType_VOICE *VOICE, SPCHNFSType_COLOUR *COLOUR, int ID_CAR); /* :178 */
}
extern "C"
{
    long SPCHNFS_D_C_IN_PURS_NEAR_PERP(SPCHNFSType_PURS_UPDT *PURS_UPDT); /* :197 */
}
extern "C"
{
    long SPCHNFS_C_D_IN_PURS_NEAR_PERP_REP_STS(SPCHNFSType_VOICE *VOICE, SPCHNFSType_COLOUR *COLOUR, int ID_CAR, SPCHNFSType_DISTANCE *DISTANCE, SPCHNFSType_POSITION *POSITION, int ID_LOCATION); /* :219 */
}
extern "C"
{
    long SPCHNFS_D_C_IN_PURS_NEAR_PERP_CONFIRM(SPCHNFSType_COLOUR *COLOUR, int ID_CAR, int ID_UNIT, SPCHNFSType_CONFIRM *CONFIRM, SPCHNFSType_PERP_NAME *PERP_NAME); /* :245 */
}
extern "C"
{
    long SPCHNFS_C_D_IN_PURS_AWAY_PERP_REPLY_STS(SPCHNFSType_VOICE *VOICE, SPCHNFSType_COLOUR *COLOUR, int ID_CAR, SPCHNFSType_POSITION *POSITION, int ID_LOCATION, SPCHNFSType_DISTANCE *DISTANCE); /* :315 */
}
extern "C"
{
    long SPCHNFS_D_C_IN_PURS_AWAY_PERP_CONFIRM(SPCHNFSType_COLOUR *COLOUR, int ID_CAR, int ID_UNIT, SPCHNFSType_CONFIRM *CONFIRM, SPCHNFSType_PERP_NAME *PERP_NAME); /* :341 */
}
extern "C"
{
    long SPCHNFS_C_D_IN_PURS_LOOK_PERP_REPLY_STS(SPCHNFSType_VOICE *VOICE, SPCHNFSType_COLOUR *COLOUR, int ID_CAR, SPCHNFSType_PERP_NAME *PERP_NAME); /* :407 */
}
extern "C"
{
    long SPCHNFS_C_C_IDLE_WINGMAN_DISAPPEARS(SPCHNFSType_VOICE *VOICE); /* :467 */
}
extern "C"
{
    long SPCHNFS_C_D_REQ_RDBLK(SPCHNFSType_VOICE *VOICE); /* :484 */
}
extern "C"
{
    long SPCHNFS_D_C_RDBLK_SPBLT_DENIED_REPLY(SPCHNFSType_vs_RDBLK_SSTRP *vs_RDBLK_SSTRP); /* :501 */
}
extern "C"
{
    long SPCHNFS_D_C_RDBLK_SPBLT_GRANT_REPLY(SPCHNFSType_vs_RDBLK_SSTRP *vs_RDBLK_SSTRP, SPCHNFSType_CONFIRM *CONFIRM); /* :519 */
}
extern "C"
{
    long SPCHNFS_D_C_RDBLK_CONFIRMED(SPCHNFSType_POSITION *POSITION, int ID_LOCATION, SPCHNFSType_DISTANCE *DISTANCE); /* :539 */
}
extern "C"
{
    long SPCHNFS_C_D_RDBLK_FAILED(SPCHNFSType_VOICE *VOICE, SPCHNFSType_COLOUR *COLOUR, int ID_CAR); /* :560 */
}
extern "C"
{
    long SPCHNFS_C_D_REQUEST_BKUP(SPCHNFSType_VOICE *VOICE, SPCHNFSType_COLOUR *COLOUR, int ID_CAR, SPCHNFSType_POSITION *POSITION, int ID_LOCATION, SPCHNFSType_DISTANCE *DISTANCE); /* :584 */
}
extern "C"
{
    long SPCHNFS_D_C_BKUP_REQUEST_GRANT_REPLY(SPCHNFSType_DISTANCE *DISTANCE, SPCHNFSType_POSITION *POSITION, int ID_LOCATION, int ID_UNIT); /* :655 */
}
extern "C"
{
    long SPCHNFS_D_C_BKUP_REQUEST_DENIED_REPLY(void); /* :675 */
}
extern "C"
{
    long SPCHNFS_C_C_NEW_OFFICER_ENGAGING(SPCHNFSType_VOICE *VOICE, int ID_UNIT); /* :728 */
}
extern "C"
{
    long SPCHNFS_C_D_PERP_SIGHTED(SPCHNFSType_VOICE *VOICE, SPCHNFSType_COLOUR *COLOUR, int ID_CAR, SPCHNFSType_DISTANCE *DISTANCE, SPCHNFSType_POSITION *POSITION, int ID_LOCATION, SPCHNFSType_PERP_NAME *PERP_NAME); /* :752 */
}
extern "C"
{
    long SPCHNFS_D_C_PERP_SIGHTED_CONFIRM(SPCHNFSType_CONFIRM *CONFIRM, int ID_UNIT); /* :776 */
}
extern "C"
{
    long SPCHNFS_C_D_PERP_LOST(SPCHNFSType_VOICE *VOICE, SPCHNFSType_COLOUR *COLOUR, int ID_CAR, SPCHNFSType_POSITION *POSITION, int ID_LOCATION, SPCHNFSType_DISTANCE *DISTANCE, SPCHNFSType_PERP_NAME *PERP_NAME); /* :800 */
}
extern "C"
{
    long SPCHNFS_D_C_PERP_LOST_CONFIRM(SPCHNFSType_COLOUR *COLOUR, int ID_CAR); /* :824 */
}
extern "C"
{
    long SPCHNFS_C_C_PERP_REAQUIRED(SPCHNFSType_VOICE *VOICE, SPCHNFSType_COLOUR *COLOUR, int ID_CAR, SPCHNFSType_POSITION *POSITION, int ID_LOCATION, SPCHNFSType_DISTANCE *DISTANCE); /* :847 */
}
extern "C"
{
    long SPCHNFS_C_D_PERP_APPREHENSION(SPCHNFSType_VOICE *VOICE, SPCHNFSType_PERP_NAME *PERP_NAME); /* :926 */
}
extern "C"
{
    long SPCHNFS_D_C_PERP_APPREHENSION_REPLY(int ID_UNIT, SPCHNFSType_CONFIRM *CONFIRM, SPCHNFSType_PERP_NAME *PERP_NAME); /* :946 */
}
extern "C"
{
    long SPCHNFS_C_D_PERP_CRASH_GEN(SPCHNFSType_VOICE *VOICE, SPCHNFSType_POSITION *POSITION, int ID_LOCATION, SPCHNFSType_COLOUR *COLOUR, int ID_CAR, SPCHNFSType_DISTANCE *DISTANCE, SPCHNFSType_PERP_NAME *PERP_NAME); /* :971 */
}
extern "C"
{
    long SPCHNFS_C_P_ARRESTED(SPCHNFSType_VOICE *VOICE, SPCHNFSType_ARREST *ARREST); /* :1014 */
}
extern "C"
{
    long SPCHNFS_C_P_WARNING(SPCHNFSType_VOICE *VOICE, SPCHNFSType_ARREST *ARREST); /* :1033 */
}
extern "C"
{
    long SPCHNFS_C_P_TICKET(SPCHNFSType_VOICE *VOICE, SPCHNFSType_ARREST *ARREST); /* :1052 */
}
extern "C"
{
    long SPCHNFS_C_P_FALSE_ARREST_BULLHORN(SPCHNFSType_VOICE *VOICE); /* :1070 */
}
extern "C"
{
    long SPCHNFS_C_D_DURING_FALSE_ARREST(SPCHNFSType_VOICE *VOICE, SPCHNFSType_PERP_NAME *PERP_NAME); /* :1088 */
}
extern "C"
{
    long SPCHNFS_C_P_BULLHORN_SPEECH(SPCHNFSType_VOICE *VOICE); /* :1106 */
}
extern "C"
{
    long SPCHNFS_S_C_SUPER_COP_ARRIVAL(SPCHNFSType_VOICE *VOICE); /* :1123 */
}
extern "C"
{
    long SPCHNFS_S_C_SUPER_COP_CRITICISM(SPCHNFSType_VOICE *VOICE); /* :1140 */
}
extern "C"
{
    long SPCHNFS_C_D_IN_PURS_NEAR_PERP_REP_LOC(SPCHNFSType_VOICE *VOICE, SPCHNFSType_POSITION *POSITION, int ID_LOCATION, SPCHNFSType_DISTANCE *DISTANCE); /* :1285 */
}
extern "C"
{
    long SPCHNFS_C_D_IN_PURS_NEAR_PERP_REP_SPD(SPCHNFSType_VOICE *VOICE, int ID_SPEED, SPCHNFSType_vs_KMH_MPH *vs_KMH_MPH); /* :1307 */
}
extern "C"
{
    long SPCHNFS_C_D_IN_PURS_AWAY_PERP_REPLY_LOC(SPCHNFSType_VOICE *VOICE, SPCHNFSType_POSITION *POSITION, int ID_LOCATION, SPCHNFSType_DISTANCE *DISTANCE, SPCHNFSType_COLOUR *COLOUR, int ID_CAR, SPCHNFSType_PERP_NAME *PERP_NAME); /* :1332 */
}
extern "C"
{
    long SPCHNFS_C_D_IN_PURS_LOOK_PERP_REPLY_LOC(SPCHNFSType_VOICE *VOICE, SPCHNFSType_POSITION *POSITION, int ID_LOCATION, SPCHNFSType_DISTANCE *DISTANCE, SPCHNFSType_COLOUR *COLOUR, int ID_CAR); /* :1360 */
}
extern "C"
{
    long SPCHNFS_D_C_INTRO_CALL(int ID_UNIT, int ID_UNIT1, SPCHNFSType_REVINTRO *REVINTRO); /* :1384 */
}
extern "C"
{
    long SPCHNFS_C_A_INTRO(SPCHNFSType_VOICE *VOICE, int ID_UNIT, int ID_UNIT1, SPCHNFSType_REVINTRO *REVINTRO); /* :1427 */
}
extern "C"
{
    long SPCHNFS_C_D_IN_PURS_PERP_AIRBORN(SPCHNFSType_VOICE *VOICE); /* :1447 */
}
extern "C"
{
    long SPCHNFS_D_C_SPBLT_CONFIRMED(SPCHNFSType_POSITION *POSITION, int ID_LOCATION, SPCHNFSType_DISTANCE *DISTANCE, int ID_UNIT, SPCHNFSType_SPIKE_BELT_SIDE *SPIKE_BELT_SIDE); /* :1468 */
}
extern "C"
{
    long SPCHNFS_C_D_REQ_SPBLT(SPCHNFSType_VOICE *VOICE); /* :1489 */
}
extern "C"
{
    long SPCHNFS_C_D_SPBLT_FAILED(SPCHNFSType_VOICE *VOICE, SPCHNFSType_COLOUR *COLOUR, int ID_CAR); /* :1508 */
}
extern "C"
{
    long SPCHNFS_W_D_RDBLK_PLC(SPCHNFSType_VOICE *VOICE, SPCHNFSType_POSITION *POSITION, int ID_LOCATION, SPCHNFSType_DISTANCE *DISTANCE); /* :1530 */
}
extern "C"
{
    long SPCHNFS_W_D_SPBLT_PLC(SPCHNFSType_VOICE *VOICE, SPCHNFSType_POSITION *POSITION, SPCHNFSType_SPIKE_BELT_SIDE *SPIKE_BELT_SIDE, int ID_UNIT, int ID_LOCATION, SPCHNFSType_DISTANCE *DISTANCE); /* :1555 */
}
extern "C"
{
    long SPCHNFS_C_D_PERP_CRASH_ROLL(SPCHNFSType_VOICE *VOICE, SPCHNFSType_POSITION *POSITION, int ID_LOCATION, SPCHNFSType_DISTANCE *DISTANCE, SPCHNFSType_PERP_NAME *PERP_NAME); /* :1581 */
}
extern "C"
{
    long SPCHNFS_D_A_CONFIRM(SPCHNFSType_CONFIRM *CONFIRM); /* :1638 */
}
extern "C"
{
    long SPCHNFS_C_D_ENDGAME(SPCHNFSType_VOICE *VOICE); /* :1655 */
}

#endif /* _GAME_COMMON_SPCHEVNT_H_ */
